hellohaptik/relements

.travis.yml, package.json, yarn.lock
=> ci(pipeline): ci pipeline fixes

src/components/Inputs/Chips/Chips.mdx
=> docs(chips): added Examples

src/components/Inputs/File/File.js, src/components/Inputs/File/File.scss, src/components/UI/Loader/Loader.scss
Fixed onUploadsComplete function
=> fix(file component): Fixed onUploadsComplete function

src/components/Inputs/RangeSlider/RangeSlider.mdx, src/components/Inputs/RangeSlider/__tests__/RangeSlider.test.js, src/components/Inputs/RangeSlider/hooks/useRangeSlider.js
adds OnBlur Listener to set values
=> fix(rangeslider): adds OnBlur Listener to set values

src/components/Inputs/Text/Text.js
Added support for onKeyDown prop
=> fix(text): added support for onKeyDown Prop

src/components/Inputs/Chips/Chips.js, src/components/Inputs/Chips/Chips.mdx, src/components/Inputs/_common/ChipsInput.js
don't show cross button when chips disabled
=> fix(chips): don't show cross button when chips disabled

src/components/Inputs/Search/Search.js, src/hooks/useEnterKey/useEnterKey.js
fixes Event Listener for Search
=> fix(search): fixes Event Listener for Search

src/components/Inputs/_common/ChipsInput.js
autofocus input field on focus of chips
=> fix(chips): autofocus input field on focus of chips

src/components/Overlays/ContextMenu/components/ContextMenuPortal.js, src/hooks/useEnterKey/useEnterKey.js
fixed global enter keydown listener
=> fix(contextmenu): fixed global enter keydown listener

src/components/Inputs/Text/Text.js, src/components/Inputs/_common/TextInput.js
=> improvement(Text): Reference update #PLAT-1074

README.md
=> fix(readme): readme changed

README.md
Updated readme for new release
=> fix(readme): updated Readme for new release

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/Dropdown.mdx
Removed arrow from disabled dropdown
=> fix(dropdown): removed arrow from disabled dropdown

src/components/Inputs/Dropdown/hooks/useKeyboardSelect.js, src/components/UI/Icon/Icon.js
icon tooltip position + dropdown enter key on enter crash fixes
=> fix(icon + dropdown): icon tooltip position + dropdown enter key crash

src/components/Inputs/Date/Date.js, src/components/Inputs/Date/Date.mdx, src/components/Inputs/Date/Date.scss, src/components/Inputs/Date/__tests__/Date.basic.test.js, src/components/Inputs/Date/components/SinglePicker/SinglePicker.scss, src/components/Inputs/RangeSlider/__tests__/RangeSlider.test.js, src/components/Inputs/RangeSlider/hooks/useRangeSlider.js, src/components/Inputs/Time/components/TimePickerInput/TimePickerInput.scss, src/components/Overlays/Tooltip/Tooltip.scss, src/components/UI/Calendar/Calendar.scss
- date picker has a new prop `withTime`
- rangeslider now respects min and max values
=> fix(inputs): datepicker with time + rangeslider fixes

src/components/Inputs/Date/Date.js, src/components/Inputs/Date/components/SinglePicker/SinglePicker.js, src/components/Inputs/Time/components/TimePicker/TimePicker.js, src/components/UI/Calendar/Calendar.js, src/components/UI/Calendar/Calendar.scss
Min/Max support
other bug fixes
=> fix(datepicker): date picker min/max support, other changes

src/components/UI/Tabs/Tabs.js
Number of references would change causing it to crash.
=> fix(tabs): crash when changing tabs dynamically

src/components/UI/Icon/utils/getIcon.js, src/icons/close-v2.svg
=> fix(Icon): Added v2 of close icon

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/components/Option/Option.js, src/components/Inputs/Dropdown/components/Options/Options.js, src/components/Inputs/Dropdown/hooks/useSearch.js
withCreate would not sometimes create an item upon clicking
=> fix(dropdown): withCreate was buggy

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/components/Option/Option.js, src/components/Inputs/Dropdown/utils/getOptions.js
Added type:create for created values
=> fix(dropdown): added type:create for created values

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/Dropdown.mdx, src/components/Inputs/Dropdown/__tests__/Dropdown.test.js, src/components/Inputs/Dropdown/components/Input/Input.js, src/components/Inputs/Dropdown/components/Options/Options.js, src/components/Inputs/Dropdown/hooks/useKeyboardSelect.js, src/components/Inputs/Dropdown/hooks/useSearch.js
Upon clearing the dropdown character by character, the dropdown would reset to the last selected option prematurely. This would make input a little harder.
=> fix(dropdown): emptying the dropdown char by char was buggy on emptying

README.md
=> fix(readme): change can styled to can be styled

src/components/Inputs/File/File.js, src/components/Inputs/File/__tests__/File.test.js
Changelog:
Updated the default browser alert with toast message from relements, whenever there's a validation error in file component.
=> enhancement(file): Update alert box UI on validation #BB-2024

src/components/UI/Button/Button.scss
This PR adds a visiual effect to button component on click as if it is pushed down.
=> fix(button): add transition effect for button on click

src/components/UI/AlertBar/AlertBar.js, src/components/UI/AlertBar/AlertBar.mdx, src/components/UI/AlertBar/AlertBar.scss, src/components/UI/AlertBar/AlertBar.storybook.js, src/components/UI/AlertBar/__tests__/AlertBar.test.js, src/components/UI/AlertBar/icons/defaultIcon.svg, src/components/UI/AlertBar/index.js, src/components/UI/AlertBar/utils.js, src/components/UI/AlertBar/variables.scss
Changelog:
Ticket: [#BB-1995](https://hello-haptik.atlassian.net/browse/BB-1995)
Component:
1 - AlertBar
- New AlertBar component added
**Demo** - https://d45baa6731c9.ngrok.io/?path=/story/components-ui-alertbar--documentation
=> feat(alert-bar): add new alert bar component

config/exports.js, src/components/Inputs/File/File.js, src/components/Inputs/File/File.mdx, src/components/Inputs/File/File.scss, src/components/Inputs/File/File.storybook.js, src/components/Inputs/File/__tests__/File.test.js
Ticket: [#BB-2166](https://hello-haptik.atlassian.net/browse/BB-2166)
Changelog:
- Add new `onUpload` prop to File component
- Uses custom function to override default file upload process
=> improvement(file): add onUpload prop to override default file upload

src/components/Inputs/ExpandableInputBar/ExpandableInputBar.js, src/components/Inputs/ExpandableInputBar/ExpandableInputBar.mdx, src/components/Inputs/ExpandableInputBar/__tests__/ExpandableInputBar.test.js
Changelog:
- Fix onClick which wasn't receiving updated values
=> fix(expandable-input-bar): fix onClick event

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/components/Input/Input.js
JIRA ticket - BB-2293
Added prefix classname & Tooltip for icon, label
=> fix(dropdown): added prefix classname & tooltip for icon

src/components/Inputs/ExpandableInputBar/ExpandableInputBar.js, src/components/Inputs/ExpandableInputBar/ExpandableInputBar.mdx, src/components/Inputs/ExpandableInputBar/ExpandableInputBar.scss, src/helpers/DocBlocks/CodeBlock/CodeBlock.js, src/icons/close-v2.svg
Ticket - BB-2292
Changelog:
- Updated styles for error/success message
- Added `disableOnlyButton` prop
=> fix(expendableinputbar): updated styles

src/components/Inputs/File/File.js
Fix custom validate check when it was bypassing customValidation even when check is true
=> fix(file): fix customValidate check

.storybook/theme.js
updated brand URL to relements homepage
=> fix(brand-url): updated brand URL to relements homepage

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/__tests__/Dropdown.test.js, src/components/Inputs/Dropdown/components/Options/Options.js, src/components/Inputs/Dropdown/components/Options/Options.scss, src/components/Inputs/Dropdown/components/UseCheckboxInput/UseCheckboxInput.js
=> feat(checkbox): added checkbox styles

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/__tests__/Dropdown.test.js, src/components/Inputs/Dropdown/components/Options/Options.js, src/components/Inputs/Dropdown/components/Options/Options.scss, src/components/Inputs/Dropdown/components/UseCheckboxInput/UseCheckboxInput.js
=> Added more checkbox

src/components/UI/Button/Button.js, src/components/UI/Button/Button.mdx, src/components/UI/Button/Button.scss, src/components/UI/Button/__tests__/Button.test.js
Added an optional secondary icon view in Button components.
=> feat(button): added secondary icon

src/components/UI/Button/Button.js, src/components/UI/Button/Button.scss
updated logic to add wrapper only when status icon is set
=> fix(button): updated logic to add wrapper only when status icon is set

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/hooks/useSearch.js
BB-2793
- Updated search to not reset on option select
=> fix(dropdown): fixed search result reset in dropdown on selection

config/rollup.config.js, src/Theme/Theme.js, src/Theme/radii.js, src/components/UI/Box/Box.js, src/components/UI/Button/ThemeButton.js
- Add layout, position, and flex capability to Box component
=> feat(box): extend box capability to layout, flex and position

src/Theme/Theme.js, src/Theme/button.js, src/Theme/shadows.js, src/Theme/space.js, src/components/UI/Button/Button.mdx, src/components/UI/Button/ThemeButton.js, src/components/UI/Button/__tests__/Button.test.js, src/helpers/DocBlocks/CodeBlock/CodeBlock.js
- Add design variants to button
https://relements.vercel.app/?path=/story/components-ui-button--documentation
=> feat(button): add design system variants

package.json
Jira: [AGCT-1088](https://hello-haptik.atlassian.net/browse/AGCT-1088)
- remove dev command because we do not use it anymore.
=> miscellaneous(package): remove dev command

README.md
=> fix: remove extra space

src/Theme/fontSizes.js, src/Theme/text.js, src/components/UI/Text/Text.js, src/components/UI/Text/Text.mdx, src/components/UI/Text/Text.storybook.js
Text variation added from the Design spec
https://relements.vercel.app/?path=/story/components-ui-text--documentation
=> feat(text): add typography variant

src/components/Inputs/Date/Date.mdx, src/components/Inputs/Date/components/RangeComparison/RangePicker.js, src/components/UI/Calendar/Calendar.js
Disable dates before start date, set max selectable compare date
Jira:  [1150](https://hello-haptik.atlassian.net/browse/AN-1150)
--
Disabled dates before start date, set max selectable compare dates
=> fix(date-picker): disable dates before start date, set max selectable compare dates

src/components/Inputs/Date/components/Comparison/Comparison.js, src/components/Inputs/Date/components/Comparison/Comparison.scss, src/components/Inputs/Date/components/Input/Input.scss, src/components/Inputs/Date/components/Inputs/Inputs.js, src/components/Inputs/Date/components/Inputs/Inputs.scss
[1150](https://hello-haptik.atlassian.net/browse/AN-1150)
Datepicker buttons ui, fixed logic for last 7 days, 30 days etc buttons
https://practical-boyd-52c19d.netlify.app/?path=/story/components-inputs-date--documentation
=> fix(date-picker): datepicker buttons ui, logic fixes

src/components/Inputs/Date/components/RangeComparison/RangePicker.js, src/components/UI/Calendar/Calendar.js
Jira:  [1150](https://hello-haptik.atlassian.net/browse/AN-1150)
--
Toggle calendar to selected month on any shortcut button clicked
=> fix(calendar): toggle calendar to selected button

src/components/Inputs/Date/components/RangeComparison/RangePicker.js, src/components/UI/Calendar/Calendar.js
Jira:  [AN-1150](https://hello-haptik.atlassian.net/browse/AN-1150)
Demo: [Link](https://605423a72d0e500007215411--practical-boyd-52c19d.netlify.app/?path=/story/components-inputs-date--documentation)
- prevent unnecessary month toggles in calendar
- removed top border from start and end dates
=> fix(calendar): remove unnecessary toogle on compare

src/components/UI/Table/Table.js, src/components/UI/Table/Table.mdx, src/components/UI/Table/components/Body.Virtual.js, src/components/UI/Table/components/Body.js, src/components/UI/Table/components/Row.js
https://hello-haptik.atlassian.net/browse/AN-1515
- Add highlight row
https://relements.vercel.app/?path=/story/components-ui-table--documentation
=> fix(table): add row highlight

src/components/UI/Table/Table.js, src/components/UI/Table/Table.mdx
https://hello-haptik.atlassian.net/browse/AN-1515
- add active index prop
https://relements.vercel.app/?path=/story/components-ui-table--documentation
=> fix(table): add active index row prop

src/components/UI/Loader/Loader.js, src/components/UI/Loader/Loader.mdx, src/components/UI/Loader/Loader.scss, src/components/UI/Loader/ThemedLoader.js
Jira:  [AGCT-1113](https://hello-haptik.atlassian.net/browse/AGCT-1113)
Add styled component capability to loader component
=> enhancement(loader): add styled component capability

src/Theme/button.js, src/components/UI/Button/Button.js, src/components/UI/Button/ThemedButton.js
Jira:  [AGCT-1118](https://hello-haptik.atlassian.net/browse/AGCT-1118)
- font sizes for the Button are defined as if the themed font size is defined as an object.
- the themed font-sizes are defined as an array of sizes. the changes are made accordingly.
--Before
--After
=> fix(button): change font-size definition

.travis.yml
=> build(scripts): update travis.yml

src/Theme/tokens.storybook.js
- add color tokens
- test release
=> fix(storybook): add color token, test release

.releaserc.js
=> fix(build): remove disabled flag

.storybook/config.js
Jira:  [AGCT-1096](https://hello-haptik.atlassian.net/browse/AGCT-1096)
=> fix(config): import order

src/Theme/dropdown.js, src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/Dropdown.mdx, src/components/Inputs/Dropdown/ThemedDropdown.js, src/components/Inputs/Dropdown/components/Options/Options.js, src/components/Inputs/Dropdown/components/WithCheckboxInput/WithCheckboxInput.js
Jira:  [BB-3348](https://hello-haptik.atlassian.net/browse/BB-3348), [BB-3889](https://hello-haptik.atlassian.net/browse/BB-3889)
---
- Added themed checkbox
- Added max height to checkbox wrapper 
- Fixed issue where dropdown's layout was messing up due to parent's display styles
- Added `style` prop for themed dropdown for adding custom styles to the dropdown wrapper
---
[Dropdown Improvements](https://sid-relements.netlify.app/?path=/story/components-inputs-dropdown--documentation)
=> improvement(dropdown): add themed checkbox and improvements

src/components/Inputs/Dropdown/ThemedDropdown.js
Jira:  [BB-3348](https://hello-haptik.atlassian.net/browse/BB-3348)
=> fix(dropdown): fix spacing in import

src/Theme/Utils.js, src/Theme/components.js, src/components/UI/Box/Usage.storybook.js, src/components/UI/Text/Text.storybook.js, src/components/UI/Text/Usage.storybook.js
https://hello-haptik.atlassian.net/browse/AN-1615
=> improvement(storybook): add usage story for Text/Box component

src/Theme/checkbox.js, src/components/Inputs/Checkbox/Checkbox.js, src/components/Inputs/Checkbox/Checkbox.mdx, src/components/Inputs/Checkbox/CheckboxItem.mdx, src/components/Inputs/Checkbox/ThemedCheckbox/ThemedCheckboxWrapper.js
Jira:  [BB-3527](https://hello-haptik.atlassian.net/browse/BB-3527)
---
- Add missing label to Themed Checkbox
- Add `Box` wrapper's doc in `Checkbox.mdx`
---
[Themed Checkbox](https://sid-relements.netlify.app/?path=/story/components-inputs-checkbox--documentation)
=> fix(checkbox): fix themed checkbox missing label

config/rollup.config.js, package.json, yarn.lock
https://hello-haptik.atlassian.net/browse/AN-1657
- Update styled-components (removed react-is dependency)
- Keep it as devDependency for component library
=> fix(build): update styled-components to remove react-is dependency

src/components/UI/Tabs/Tabs.js, src/components/UI/Tabs/Tabs.mdx, src/components/UI/Tabs/ThemedTabs.js, src/components/UI/Tabs/components/TabsItem.js, src/components/UI/Tabs/components/ThemedTabsItem.js
Jira:  [AGCT-1225](https://hello-haptik.atlassian.net/browse/AGCT-1225)
--
- Migrate Tabs component to new design systems
--
-- Changes in Relements
Test Link: https://devswapnil.hellohaptik.com/relements/?path=/story/components-ui-tabs--documentation
=> feat(tabs): migrate to new design systems

src/hooks/usePositioner/usePositioner.js
Jira:  [AGCT-1333](https://hello-haptik.atlassian.net/browse/AGCT-1333)
- fix alignment of arrow of tooltip 
- before fix
- after fix
=> fix(tooltip): alignment fix of tooltip

src/Theme/dropdown.js, src/Theme/textInput.js, src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/Dropdown.mdx, src/components/Inputs/Dropdown/ThemedDropdown.js, src/components/Inputs/Dropdown/components/Input/Input.js, src/components/Inputs/Dropdown/components/Option/Option.js, src/components/Inputs/Dropdown/components/Options/Options.js, src/components/Inputs/Text/Text.js, src/components/Inputs/Text/Text.mdx, src/components/Inputs/_common/TextInput.js, src/components/Inputs/_common/ThemedTextInput.js
Jira:  [AN-1715](https://hello-haptik.atlassian.net/browse/AN-1715)
--
Size variant small for input and integrated for dropdown
https://60c9aea10a6a260007e0d401--gifted-wing-304c8e.netlify.app/?path=/story/components-inputs-text--documentation
=> fix(input): size variant for input/dropdown

src/components/UI/Icon/Icon.js, src/components/UI/Table/Table.js, src/components/UI/Table/Table.storybook.js, src/components/UI/Table/components/Body.Virtual.js, src/components/UI/Table/components/Header.js, src/components/UI/Table/components/Row.js
Jira:  [AGCT-1341](https://hello-haptik.atlassian.net/browse/AGCT-1341)
--
- Add tooltip info to Table Header
- Add tooltip to overflown columns
--
=> fix(table): add tooltip support to themed table

.eslintrc, package.json, yarn.lock
Jira:  [AGCT-1342](https://hello-haptik.atlassian.net/browse/AGCT-1342)
--
This Plugin will help us in the following.
- To enforce the rules of hooks.
- Prevent common coding mistakes that cause bugs. – (missing dependency in react hooks)
--
=> build(eslintrc): add and enable react hooks plugin

src/components/Context/Provider.js
Jira:  [AGCT-1369](https://hello-haptik.atlassian.net/browse/AGCT-1369)
--
(REMOVE ME) 
-  wrap getTheme function in useMemo to avoid re-calculation
=> fix(provider): wrap getTheme function in useMemo to avoid re-calculation

src/components/Inputs/Dropdown/Dropdown.js, src/components/Inputs/Dropdown/__tests__/DropdownOption.test.js, src/components/Inputs/Dropdown/components/Option/Option.js, src/components/Inputs/Dropdown/components/Options/Options.js
Jira:  [AGCT-1365](https://hello-haptik.atlassian.net/browse/AGCT-1365)
- there is two events onBlur and onClick 
- when someone click this div, we want first onClick to dispatch first but here onBlur get dispatch first
- so I have added the onMouseDown event and increased the blurCount value 
- logic inside onBlur checks value of blurCount  
- https://quizzical-edison-4be2b1.netlify.app/
=> fix(dropdown): onClick with search input in dropdown

package.json, yarn.lock
Jira:  [IS-89](https://hello-haptik.atlassian.net/browse/IS-89), [FRONTEND-13](https://hello-haptik.atlassian.net/browse/FRONTEND-13)
--
- Updated react-syntax-highlighter package
=> refactor: package updated
